from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import OperationViewSet, FabricTypeViewSet, DistinctiveFeatureViewSet, GarmentTypeViewSet

router = DefaultRouter()
router.register(r'operations', OperationViewSet)
router.register(r'fabric_types', FabricTypeViewSet)
router.register(r'distinctive_features', DistinctiveFeatureViewSet)
router.register(r'garment_types', GarmentTypeViewSet)



from .views import (
    register_view,
    login_view,
    logout_view,
    change_password_view,
    password_reset_request_view,
    password_reset_confirm_view,
    factoryowner_profile_view,
    operator_profile_view,
    home_view,
    perfil_view,
    editar_perfil_view,
    show_plans_view,
    add_operator_view,
    operator_list,
    edit_operator_view,
    delete_operator_view,
    add_client_view,
    client_list_view,
    edit_client_view,
    delete_client_view,
    add_factory_admin_view,
    factory_admin_list_view,
    add_garment_type_view, 
    garment_type_list_view,
    email_confirm_view,
    register_view,
    dashboard_estandar_fo_view,
    add_remission_view,
    remission_list_view,
    update_remission_view,
    remission_detail_view,
    delete_remission_view,
    gestion_remisiones_view,
    add_cost_simulation_view, 
    cost_simulation_detail_view, 
    update_cost_simulation_view, 
    delete_cost_simulation_view, 
    cost_simulation_list_view,
    add_profit_simulation_view,
    profit_simulation_list_view,
    add_cutting_table_view,
    cutting_table_list_view,
    garment_part_create_view,
    garment_part_list_view,
    create_garment_type_with_parts,
    gestion_prendas_view,
    size_list,
    size_create,
    size_detail,
    size_edit,
    size_delete,
    OperationListView,
    OperationDetailView,
    OperationCreateView,
    OperationUpdateView,
    OperationDeleteView,
    update_productivity_level_view,
    ErrorView,
    fabric_type_list_view, 
    FabricTypeCreateView, 
    FabricTypeUpdateView,
    FabricTypeDeleteView,
    get_unit_price,
    add_distinctive_feature,
    CuttingServiceCreateView,
    CuttingServiceDetailView,
    CuttingServiceUpdateView,
    CuttingServiceDeleteView,
    CuttingServiceListView,
    add_remission_step2_view,
)

urlpatterns = [
    path('api/', include(router.urls)),
    path('registro/', register_view, name='registro'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cambio_contrasena/', change_password_view, name='cambio_contrasena'),
    path('restablecer_contrasena_solicitud/', password_reset_request_view, name='restablecer_contrasena_solicitud'),
    path('restablecer_contrasena_confirmacion/', password_reset_confirm_view, name='restablecer_contrasena_confirmacion'),
    path('profile/factoryowner/dashboard_estandar_fo/', dashboard_estandar_fo_view, name='dashboard_estandar_fo'),
    path('profile/factoryowner/', factoryowner_profile_view, name='factoryowner_perfil'),
    path('profile/operator/', operator_profile_view, name='operator_perfil'),
    path('', home_view, name='inicio'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('perfil/', perfil_view, name='perfil'),
    path('editar_perfil/', editar_perfil_view, name='editar_perfil'),
    path('planes/', show_plans_view, name='show_plans'),
    path('agregar-operador/', add_operator_view, name='add_operator'),
    path('lista-operadores/', operator_list, name='operator_list'),
    path('editar-operador/<int:operator_id>/', edit_operator_view, name='edit_operator'),
    path('eliminar-operador/<int:operator_id>/', delete_operator_view, name='delete_operator'),
    path('agregar_cliente/', add_client_view, name='add_client'),
    path('clients/', client_list_view, name='client_list'),
    path('editar-cliente/<int:client_id>/', edit_client_view, name='edit_client'),
    path('eliminar-cliente/<int:client_id>/', delete_client_view, name='delete_client'),
    path('agregar_admin/', add_factory_admin_view, name='add_factory_admin'),
    path('listar_admins/', factory_admin_list_view, name='factory_admin_list'),
    path('add_garment_type/', add_garment_type_view, name='add_garment_type'),
    path('garment_type_list/', garment_type_list_view, name='garment_type_list'),
    path('get_unit_price/<int:garment_type_id>/', views.get_unit_price, name='get_unit_price'),
    path('email_confirm/<str:token>/', email_confirm_view, name='email_confirm'),  
    path('add_remission/', add_remission_view, name='add_remission'),
    path('remission_list/', remission_list_view, name='remission_list'),
    path('update_remission/<int:remission_id>/', update_remission_view, name='update_remission'),
    path('remission_detail/<int:remission_id>/', remission_detail_view, name='remission_detail'),
    path('delete_remission/<int:remission_id>/', delete_remission_view, name='delete_remission'),
    path('gestion_remisiones/', gestion_remisiones_view, name='gestion_remisiones'),
    path('cost_simulation/add/', add_cost_simulation_view, name='add_cost_simulation'),
    path('cost_simulation/<int:id>/detail/', cost_simulation_detail_view, name='cost_simulation_detail'),
    path('cost_simulation/<int:id>/update/', update_cost_simulation_view, name='update_cost_simulation'),
    path('cost_simulation/<int:id>/delete/', delete_cost_simulation_view, name='delete_cost_simulation'),
    path('cost_simulation/list/', cost_simulation_list_view, name='cost_simulation_list'),
    path('profit_simulation/add/', add_profit_simulation_view, name='add_profit_simulation'),
    path('profit_simulation/', profit_simulation_list_view, name='profit_simulation_list'),
    path('cutting_table/', cutting_table_list_view, name='cutting_table_list'),
    path('cutting_table/add/', add_cutting_table_view, name='add_cutting_table'),
    path('garment_part/create/', garment_part_create_view, name='garment_part_create'),
    path('garment_type/<int:garment_type_id>/parts/', garment_part_list_view, name='garment_part_list'),
    path('create_garment_type_with_parts/', create_garment_type_with_parts, name='create_garment_type_with_parts'),
    path('gestion_prendas/', gestion_prendas_view, name='gestion_prendas'),
    path('size_list/', size_list, name='size_list'),
    path('size/create/', size_create, name='size_create'),
    path('size/<int:pk>/', size_detail, name='size_detail'),
    path('size/<int:pk>/edit/', size_edit, name='size_edit'),
    path('size/<int:pk>/delete/', size_delete, name='size_delete'),
    path('operations/', OperationListView.as_view(), name='operation_list'),
    path('operations/<int:pk>/', OperationDetailView.as_view(), name='operation_detail'),
    path('operations/add/', OperationCreateView.as_view(), name='operation_create'),
    path('operations/<int:pk>/edit/', OperationUpdateView.as_view(), name='operation_edit'),
    path('operations/<int:pk>/delete/', OperationDeleteView.as_view(), name='operation_delete'),
    path('operation_list/', OperationListView.as_view(), name='operation_list'),
    path('update_productivity_level/<int:pk>/', update_productivity_level_view, name='update_productivity_level'),
    path('error/', views.ErrorView.as_view(), name='error_page'),
    path('fabric_type_list/', fabric_type_list_view, name='fabric_type_list'),
    path('fabrictype/create/', FabricTypeCreateView.as_view(), name='fabric_type_create'),
    path('fabrictype/update/<int:pk>/', FabricTypeUpdateView.as_view(), name='fabric_type_update'),
    path('fabrictype/delete/<int:pk>/', FabricTypeDeleteView.as_view(), name='fabric_type_delete'),
    path('add_distinctive_feature/', views.add_distinctive_feature, name='add_distinctive_feature'),
    path('cutting_service/new/', CuttingServiceCreateView.as_view(), name='cutting_service_create'),
    path('cutting_service/<int:pk>/', CuttingServiceDetailView.as_view(), name='cutting_service_detail'),
    path('cutting_service/<int:pk>/edit/', CuttingServiceUpdateView.as_view(), name='cutting_service_edit'),
    path('cutting_service/<int:pk>/delete/', CuttingServiceDeleteView.as_view(), name='cutting_service_delete'),
    path('cutting_services/', CuttingServiceListView.as_view(), name='cutting_service_list'),
    path('add_remission_step2/', views.add_remission_step2_view, name='add_remission_step2'),
]
